{
 "title": "Flask Prometheus Dashboard",
 "time": { "from": "2025-12-12T11:01:36.871Z", "to": "2025-12-12T13:06:02.471Z" },
 "panels": [
  {
   "title": "Request Duration (Average)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum[5m]) / rate(flask_http_request_duration_seconds_count[5m])"
    }
   ]
  },
  {
   "title": "Requests per Second (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total[1m])"
    }
   ]
  },
  {
   "title": "Status Codes (200 vs 500)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(flask_http_request_total{status=\"200\"}[5m])",
     "legendFormat": "200 OK"
    },
    {
     "expr": "rate(flask_http_request_total{status=\"500\"}[5m])",
     "legendFormat": "500 Error"
    }
   ]
  }
 ]
}